/// Achievement configuration for mg-game-0013
/// Auto-generated by achievement_system_activation.dart

import 'package:mg_common_game/systems/progression/achievement_manager.dart';

class AchievementConfig {
  static void registerAchievements(AchievementManager manager) {

    // Welcome Aboard
    manager.registerAchievement(Achievement(
      id: 'first_login',
      title: 'Welcome Aboard',
      description: 'Log in for the first time',
      iconAsset: 'assets/icons/achievements/first_login.png',
    ));

    // Thousand Gold
    manager.registerAchievement(Achievement(
      id: 'gold_1000',
      title: 'Thousand Gold',
      description: 'Accumulate 1,000 gold',
      iconAsset: 'assets/icons/achievements/gold_1000.png',
    ));

    // Ten Thousand Gold
    manager.registerAchievement(Achievement(
      id: 'gold_10000',
      title: 'Ten Thousand Gold',
      description: 'Accumulate 10,000 gold',
      iconAsset: 'assets/icons/achievements/gold_10000.png',
    ));

    // Level 10
    manager.registerAchievement(Achievement(
      id: 'level_10',
      title: 'Level 10',
      description: 'Reach level 10',
      iconAsset: 'assets/icons/achievements/level_10.png',
    ));

    // Level 25
    manager.registerAchievement(Achievement(
      id: 'level_25',
      title: 'Level 25',
      description: 'Reach level 25',
      iconAsset: 'assets/icons/achievements/level_25.png',
    ));

    // Centurion
    manager.registerAchievement(Achievement(
      id: 'games_100',
      title: 'Centurion',
      description: 'Play 100 games',
      iconAsset: 'assets/icons/achievements/games_100.png',
    ));

    // Week Warrior
    manager.registerAchievement(Achievement(
      id: 'streak_7',
      title: 'Week Warrior',
      description: 'Play for 7 consecutive days',
      iconAsset: 'assets/icons/achievements/streak_7.png',
    ));

    // First Victory
    manager.registerAchievement(Achievement(
      id: 'first_victory',
      title: 'First Victory',
      description: 'Win your first battle',
      iconAsset: 'assets/icons/achievements/first_victory.png',
    ));

    // Winning Streak
    manager.registerAchievement(Achievement(
      id: 'winning_streak',
      title: 'Winning Streak',
      description: 'Win 5 battles in a row',
      iconAsset: 'assets/icons/achievements/winning_streak.png',
    ));

    // Battle Veteran
    manager.registerAchievement(Achievement(
      id: 'battle_veteran',
      title: 'Battle Veteran',
      description: 'Fight 100 battles',
      iconAsset: 'assets/icons/achievements/battle_veteran.png',
    ));

    // Boss Conqueror
    manager.registerAchievement(Achievement(
      id: 'boss_conqueror',
      title: 'Boss Conqueror',
      description: 'Defeat 5 boss enemies',
      iconAsset: 'assets/icons/achievements/boss_conqueror.png',
    ));

    // Set up achievement unlock callback for rewards
    manager.onAchievementUnlocked = (achievement) {
      _grantAchievementReward(achievement);
    };
  }

  static void _grantAchievementReward(Achievement achievement) {
    // Grant milestone rewards based on completion percentage
    // This is called automatically when an achievement is unlocked
    
    // TODO: Implement reward distribution logic
    // Example: Grant gold, gems, or other rewards
  }

  static double getCompletionPercentage(AchievementManager manager) {
    if (manager.totalCount == 0) return 0.0;
    return manager.unlockedCount / manager.totalCount;
  }

  static void checkMilestoneRewards(AchievementManager manager) {
    final completion = getCompletionPercentage(manager);
    
    // 25% milestone
    if (completion >= 0.25) {
      // Grant 25% milestone reward
    }
    
    // 50% milestone
    if (completion >= 0.50) {
      // Grant 50% milestone reward
    }
    
    // 75% milestone
    if (completion >= 0.75) {
      // Grant 75% milestone reward
    }
    
    // 100% milestone (all achievements)
    if (completion >= 1.0) {
      // Grant 100% milestone reward
    }
  }
}
